change dotfiles for me

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -151,8 +151,8 @@ then
   fi
 fi
 
-jldeenMods () {
-  info "starting jldeen mods"
+trMods () {
+  info "starting 2rage mods"
   #backup old bin, if exists
   if [ -d $HOME/bin ]; then
     info "current $HOME/bin folder, checking for existing symlink"
@@ -167,23 +167,12 @@ jldeenMods () {
   fi
 }
 
-jd_Symlinks () {
+tr_Symlinks () {
   # symlink .dotfiles bin to ~
   ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlink for $HOME/bin folder created"
 
   # symlink .dotfiles tmux to ~
   ln -s $HOME/.dotfiles/tmux $HOME/.tmux && success "symlink for $HOME/.tmux folder created"
-
-  # symlink VSCode User Settings
-  if [ -d $HOME/Library/Application\ Support/Code/User ] ; then
-    echo "Making backup of current settings.json and creating symlink..."
-    echo ''
-    mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.old.json && success "settings.old.json created"
-    ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json && success "settings.json for vs code symlink created"
-  else
-    info "symlink for vs code settings not created"
-    echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
-  fi
 
   # airport symlink
   if ! [ -f /usr/local/bin/airport ]
@@ -195,12 +184,12 @@ jd_Symlinks () {
     fi
 }
 
-jdcolors () {
+trColors () {
   # colorls setup
   sudo gem install colorls && success 'ls colors have been configured'
 }
 
-jdcrontab () {
+trCrontab () {
   #crontab additions
   add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
     if [[ $? -eq 0 ]]
@@ -235,9 +224,9 @@ jdcrontab () {
   success "speedtest-cli bandwidth.json created"
 }
 
-jditermConfig () {
+trItermConfig () {
   # iterm2 config
-  read -p "Do you currently use iTerm2 and would you like to set jldeen's custom colors? y/n " -n 1 -r
+  read -p "Do you currently use iTerm2 and would you like to set 2rage's custom colors? y/n " -n 1 -r
   echo ''
   if [[ $REPLY =~ ^[Yy]$ ]]
   then
@@ -247,22 +236,22 @@ jditermConfig () {
     defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
       if [[ $? -eq 0 ]]
       then
-          success "successfully configured iTerm2 to use jldeen's custom colors..."
+          success "successfully configured iTerm2 to use 2rage's custom colors..."
       else
-          fail "failed to apply jldeen's custom colors..." >&2
+          fail "failed to apply 2rage's custom colors..." >&2
   fi
   else 
-      info "You chose not to use iTerm2 or jldeen's custom colors."
+      info "You chose not to use iTerm2 or 2rage's custom colors."
   fi
 }
 
-jdFontSetup () {
+trFontSetup () {
   # install Source Code Pro nerd font
   cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
   success "Source Code Pro font copied successfully!"
 }
 
-jdconfigFix () {
+trConfigFix () {
   # .config permissions fix
   if [ -d "$HOME/.config" ]; then
     info "$HOME/.config doesn't exist, nothing to fix"
@@ -272,12 +261,12 @@ jdconfigFix () {
   fi
 }
 
-jldeenMods
-jd_Symlinks
-jdcolors
+trMods
+tr_Symlinks
+trColors
 #jdcrontab
-jditermConfig
-jdFontSetup
-jdconfigFix
+trItermConfig
+trFontSetup
+trConfigFix
 
-success 'Badass macOS terminal installed!'
+success 'MacOS terminal installed!'
